version: "3.8"

networks:
  site-manager:
    driver: bridge

volumes:
  site-manager-db:

services:
  api:
    image: site-manager:latest
    container_name: site-manager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3001"
      - "3001:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - site-manager