version: "3.8"

networks:
  site-manager:
    driver: bridge

services:
  api:
    image: site-manager-api:latest
    container_name: site-manager-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - site-manager
    volumes:
      - ${SITES_AVAILABLE_PATH}:/sites-available