version: "3.8"

networks:
  site-manager:
    driver: bridge

volumes:
  site-manager-db:

services:
  api:
    image: site-manager:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - site-manager
