export { default as Home } from './Home.vue';
export { default as Login } from './Login.vue';
export { default as Register } from './Register.vue';
export { default as Dashboard } from './Dashboard.vue';
export { default as Overview } from './Overview.vue';
export { default as Sites } from './Sites.vue';
export { default as Site } from './Site.vue';
export { default as Domains } from './Domains.vue';
export { default as Settings } from './Settings.vue';
