name: Build and push command-service binary

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'command-service/**'

jobs:
  build_binary:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    name: Build command service binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        working-directory: ./command-service
        run: |
          go build -o command-service .
          echo "Binary built successfully"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: command-service
          path: ./command-service/command-service