name: Build release Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      VITE_BASE: ${{ env.VITE_BASE }}
      VITE_API: ${{ env.VITE_API }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest