name: Build release Docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      VITE_BASE: ${{ vars.VITE_BASE }}
      VITE_API: ${{ vars.VITE_API }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: Define image tag
        run: |
          echo TAG=latest >> $GITHUB_ENV
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo TAG=pr-${{ github.event.number }} >> $GITHUB_ENV
          fi

      - name: Build and push image
        run: echo ${{ env.TAG }}
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/${{ github.repository }}:latest
#          build-args: |
#            VITE_BASE=${{ vars.VITE_BASE }}
#            VITE_API=${{ vars.VITE_API }}